### ISSUE TITLE
Positioning with BLTouch

### ISSUE THREAD

**Issue by Guenda85** [npiegdon/bed-inspector#8]
unfortunately now where points are drawn i have another issue :-)

after centering the machine (circle is drawn at 117.5mm) i want to measure the corners.
This will just send 4 G1 codes to the corners according the bed size entered and do a probe.

starting with first corner at Y235 X0 it moves the noozle to the right place - but probing is not possible as the BLTouch of couse is out of bed:
![IMG_1003](https://user-images.githubusercontent.com/45709724/76095206-2d82d880-5fc4-11ea-9175-88de621dba77.jpg)

G28 obviously centers the probe to the middle of the bed, not the noozle

my z-probe offsets according to marlin2 firmware:
echo:; Z-Probe Offset (mm):
echo:  M851 X-43.00 Y-5.00 Z-2.90

**Comment by Guenda85** [comment]
you can also see it here:

**X:160.00 Y:122.00 Z:12.90** E:0.00 Count X:12800 Y:9760 Z:5160
-> this is the noozle position according to Z-Probe Offsets

**Bed X: 117,00 Y: 117,00 Z: -0,00**
-> this is the result of the probe - coordinates are according to position of Probe

**Comment by mPixels** [comment]
Can confirm this is happening. It is relation the where the probe is attached, some are on the left some are on right, or even front, at different distances. We need a way to state where the probe is in relation to the nozzle or bed.

**Comment by Guenda85** [comment]
Any solution to this in the making?

**Comment by npiegdon** [comment]
In the v2 release, printer bed dimensions are now specified as left/right and top/bottom pairs (instead of width and height), so you can now cut off a little bit of the bed on any side to compensate for the probe going over the edge.

This is a more manual workaround than handling the Z-Probe offset value in the Marlin firmware specifically, but I like it because it's also more general purpose.  Using the same feature you could, say, run a "full" scan on just a portion of your bed that you were curious about.
